version: 0.2

phases:
  pre_build:
    commands:
      # - export NEXT_PUBLIC_USER_POOL_ID=$USER_POOL_ID
      # - export NEXT_PUBLIC_CLIENT_ID=$CLIENT_ID
      - echo NEXT_PUBLIC_USER_POOL_ID=${USER_POOL_ID} >> .env
      - echo NEXT_PUBLIC_CLIENT_ID=${CLIENT_ID} >> .env
      - echo NEXT_PUBLIC_NODE_ENV=${NODE_ENV} >> .env
      - echo NEXT_PUBLIC_BASE_URL=${BASE_URL} >> .env
      - echo "Installing dependencies..."
      - npm install
      - echo Running ESLint...
      - npx eslint ./
      - echo Running tests...
      - npm test
      # - echo Exporting environment variables to .env.production...
      # - env | grep -e NEXT_PUBLIC_ >> .env.production
      - echo Building the Next.js app...
      - npm run build
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 352866427157.dkr.ecr.ap-southeast-2.amazonaws.com/frontend-main-repository
      - echo Building the Docker image...
      - docker build -t frontend-main .
      - echo Tagging the Docker image...
      - docker tag frontend-main:latest 352866427157.dkr.ecr.ap-southeast-2.amazonaws.com/frontend-main-repository:$NODE_ENV
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 352866427157.dkr.ecr.ap-southeast-2.amazonaws.com/frontend-main-repository:$NODE_ENV
      - echo Generating image definitions file...
      - printf '[{"name":"frontend-main-%s-container","imageUri":"352866427157.dkr.ecr.ap-southeast-2.amazonaws.com/frontend-main-repository:%s"}]' $NODE_ENV $NODE_ENV > imagedefinitions.json

artifacts:
  files: imagedefinitions.json